service: hms-email-service

provider:
  name: aws
  runtime: python3.9
  environment:
    SMTP_EMAIL: ${env:SMTP_EMAIL}
    SMTP_PASSWORD: ${env:SMTP_PASSWORD}

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: get
          cors: true
      - http:
          path: send-email
          method: post
          cors: true